"""empty message

Revision ID: d69d9f923521
Revises: a54f78c076da
Create Date: 2024-05-06 17:13:37.944287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69d9f923521'
down_revision = 'a54f78c076da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
